version: "3.1"
services:

  db:
    build:
      context: db
    image: postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: itender

    ports:
      - 25432:5432

  api:
    build:
      context: api
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - db
    environment:
      - spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:postgresql://db:5432/itender
      - spring.datasource.username=postgres
      - spring.datasource.password=1234
      - spring.datasource.driver.class=com.postgres.jdbc.Driver
      - spring.jpa.properties.hibernate.format_sql=true
      - spring.sql.init.mode=always
      - spring.datasource.initialize=true
      - springdoc.show.actuator=true
      - JWT_SECRET=rWBYr(P3Ye&7Z!m7
      - springdoc.api-docs.path=/itender-openapi
      - server.servlet.context-path=/api
      - FRONT_URL_QR=http://localhost:4200/home/
      - spring.servlet.multipart.max-file-size=10MB
      - spring.servlet.multipart.max-request-size=10MB
      - spring.sql.init.data-locations=classpath:init.sql
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  angular-service:
    container_name: iTenderAngular
    build: 
      context: ./front
      dockerfile: ./Dockerfile
    ports: 
      - "4200:80"
    environment:
      - apiUrl=http://192.168.236.230:8080/api

volumes:
  postgresql-data: