version: "3.1"
services:
  db:
    build:
      context: db
    image: itender/db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: itender
    ports:
      - 25432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  api:
    build:
      context: api
    image: itender/api
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  postgresql-data: