version: "3.1"
services:
  api:
    build: api
    image: itender-docker
    ports:
      - 8080:8080
  db:
    container_name: itender-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: itender
    build: db
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
volumes:
  postgresql-data: