version: "3.1"
services:
  api:
    container_name: villa-amelia-app
    build:
      context: ./api
      dockerfile: Dockerfile
    image: villa-amelia-docker
    ports:
      - 8080:8080
  db:
    build: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: villa-amelia
    image: db
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
volumes:
  postgresql-data: