version: "3.1"
services:

  db:
    build:
      context: db
    image: postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: itender

    ports:
      - 25432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  api:
    build:
      context: api
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:postgresql://db:5432/itender
      - spring.datasource.username=postgres
      - spring.datasource.password=1234
      - spring.datasource.driver.class=com.postgres.jdbc.Driver
      - spring.jpa.properties.hibernate.format_sql=true
      - spring.sql.init.mode=always
      - spring.datasource.initialize=true
      - springdoc.show.actuator=true
      - JWT_SECRET=rWBYr(P3Ye&7Z!m7
      - springdoc.api-docs.path=/itender-openapi
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgresql-data: